import { DENUNCIA_STATUS, PRIORITY } from '@/utils/constants'

// ── Credenciales de acceso (AuthContext mock) ──────────────────────────────────
export const MOCK_CREDENTIALS = [
  {
    email: 'operador@municipio.gob',
    password: '123456',
    token: 'mock-token-operador',
    user: { id: 2, names: 'María', lastname: 'García', email: 'operador@municipio.gob', role: 'Operador de Call Center', unitId: 1 },
  },
  {
    email: 'campo@municipio.gob',
    password: '123456',
    token: 'mock-token-campo',
    user: { id: 3, names: 'Juan', lastname: 'Pérez', email: 'campo@municipio.gob', role: 'Personal de Campo', unitId: 2 },
  },
  {
    email: 'admin@municipio.gob',
    password: '123456',
    token: 'mock-token-admin',
    user: { id: 1, names: 'Ana', lastname: 'Rodríguez', email: 'admin@municipio.gob', role: 'Administrador', unitId: null },
  },
]

// ── Denuncias (formato frontend mapeado) ───────────────────────────────────────
export const MOCK_DENUNCIAS = [
  {
    _id: 1,
    id: 'DEN-2026-001',
    titulo: 'Bache profundo en Av. Libertad',
    descripcion: 'Bache de aproximadamente 50cm de diámetro en el carril derecho, representa peligro para motociclistas.',
    categoria: 'Baches y vialidad',
    area: 'Área de Vialidad',
    estado: DENUNCIA_STATUS.PENDIENTE,
    prioridad: PRIORITY.URGENTE,
    fecha: '2026-03-28T09:15:00',
    ciudadano: 'Carlos Méndez',
    telefono: '555-0101',
    direccion: 'Av. Libertad #450, Col. Centro',
    operador: 'María García',
    tecnicoResponsable: null,
    lat: 19.4326,
    lng: -99.1332,
    arrivalTime: null,
    finishTime: null,
    technicalNotes: null,
    materialsUsed: null,
    resolutionResult: null,
    operatorSignature: null,
    evidence: null,
    images: [],
  },
  {
    _id: 2,
    id: 'DEN-2026-002',
    titulo: 'Fuga de agua en calle Morelos',
    descripcion: 'Fuga constante de agua potable desde hace 3 días. El agua corre por toda la calle.',
    categoria: 'Agua y drenaje',
    area: 'Área de Agua y Drenaje',
    estado: DENUNCIA_STATUS.EN_PROCESO,
    prioridad: PRIORITY.ALTA,
    fecha: '2026-03-27T14:30:00',
    ciudadano: 'Ana López',
    telefono: '555-0102',
    direccion: 'Calle Morelos #123, Col. Juárez',
    operador: 'María García',
    tecnicoResponsable: 'Juan Pérez',
    lat: 19.4284,
    lng: -99.1476,
    arrivalTime: '2026-03-28T08:00:00',
    finishTime: null,
    technicalNotes: 'Fuga detectada en tubería de 3 pulgadas. Se requiere sustitución del segmento dañado.',
    materialsUsed: 'Tubería PVC 3", bridas, sellador epóxico',
    resolutionResult: null,
    operatorSignature: null,
    evidence: 'https://placehold.co/600x400/4ac1e0/ffffff?text=Evidencia+fuga',
    images: [
      { id: 1, url: 'https://placehold.co/600x400/4ac1e0/ffffff?text=ANTES+fuga', type: 'BEFORE' },
    ],
  },
  {
    _id: 3,
    id: 'DEN-2026-003',
    titulo: 'Luminaria fundida en parque',
    descripcion: 'Tres luminarias sin funcionar en el parque central, zona insegura por las noches.',
    categoria: 'Alumbrado público',
    area: 'Área de Alumbrado Público',
    estado: DENUNCIA_STATUS.PENDIENTE,
    prioridad: PRIORITY.ALTA,
    fecha: '2026-03-27T11:00:00',
    ciudadano: 'Roberto Sánchez',
    telefono: '555-0103',
    direccion: 'Parque Central, entrada norte',
    operador: null,
    tecnicoResponsable: null,
    lat: 19.4352,
    lng: -99.1412,
    arrivalTime: null,
    finishTime: null,
    technicalNotes: null,
    materialsUsed: null,
    resolutionResult: null,
    operatorSignature: null,
    evidence: null,
    images: [],
  },
  {
    _id: 4,
    id: 'DEN-2026-004',
    titulo: 'Acumulación de basura en esquina',
    descripcion: 'Vecinos depositan basura en la esquina sin respetar horarios de recolección.',
    categoria: 'Basura y limpieza',
    area: 'Área de Limpieza y Residuos',
    estado: DENUNCIA_STATUS.RESUELTA,
    prioridad: PRIORITY.MEDIA,
    fecha: '2026-03-25T08:45:00',
    ciudadano: 'Laura Martínez',
    telefono: '555-0104',
    direccion: 'Esquina de Hidalgo y 5 de Mayo',
    operador: 'Juan Pérez',
    tecnicoResponsable: 'Juan Pérez',
    lat: 19.4310,
    lng: -99.1350,
    arrivalTime: '2026-03-25T10:00:00',
    finishTime: '2026-03-26T16:30:00',
    technicalNotes: 'Limpieza completa del área realizada. Se colocaron señalizaciones de horario.',
    materialsUsed: 'Sacos de basura, escobas, señales metálicas',
    resolutionResult: 'Área limpia y señalizada. Se notificó a vecinos sobre horarios de recolección.',
    operatorSignature: null,
    evidence: null,
    images: [
      { id: 2, url: 'https://placehold.co/600x400/4ac1e0/ffffff?text=ANTES+basura', type: 'BEFORE' },
      { id: 3, url: 'https://placehold.co/600x400/22c55e/ffffff?text=DESPUÉS+limpio', type: 'AFTER' },
    ],
  },
  {
    _id: 5,
    id: 'DEN-2026-005',
    titulo: 'Ruido excesivo de bar nocturno',
    descripcion: 'Bar "La Terraza" opera con música a alto volumen hasta las 4am entre semana.',
    categoria: 'Ruido excesivo',
    area: 'Área de Tránsito',
    estado: DENUNCIA_STATUS.EN_PROCESO,
    prioridad: PRIORITY.MEDIA,
    fecha: '2026-03-26T22:10:00',
    ciudadano: 'Patricia Gómez',
    telefono: '555-0105',
    direccion: 'Calle Reforma #89, Col. Centro',
    operador: 'María García',
    tecnicoResponsable: null,
    lat: 19.4298,
    lng: -99.1388,
    arrivalTime: '2026-03-27T09:00:00',
    finishTime: null,
    technicalNotes: 'Se verificó el establecimiento. Opera con permiso pero excede los límites permitidos de ruido (>65dB nocturno).',
    materialsUsed: null,
    resolutionResult: null,
    operatorSignature: null,
    evidence: null,
    images: [],
  },
  {
    _id: 6,
    id: 'DEN-2026-006',
    titulo: 'Semáforo descompuesto',
    descripcion: 'Semáforo en intermitente permanente, cruces peligrosos en hora pico.',
    categoria: 'Baches y vialidad',
    area: 'Área de Vialidad',
    estado: DENUNCIA_STATUS.PENDIENTE,
    prioridad: PRIORITY.URGENTE,
    fecha: '2026-03-28T07:30:00',
    ciudadano: 'Miguel Torres',
    telefono: '555-0106',
    direccion: 'Cruce Av. Insurgentes y Calle 10',
    operador: null,
    tecnicoResponsable: null,
    lat: 19.4268,
    lng: -99.1520,
    arrivalTime: null,
    finishTime: null,
    technicalNotes: null,
    materialsUsed: null,
    resolutionResult: null,
    operatorSignature: null,
    evidence: null,
    images: [],
  },
  {
    _id: 7,
    id: 'DEN-2026-007',
    titulo: 'Juegos infantiles dañados',
    descripcion: 'Resbaladilla rota y columpios sin cadenas en parque de la colonia.',
    categoria: 'Espacios públicos',
    area: 'Área de Espacios Públicos',
    estado: DENUNCIA_STATUS.PENDIENTE,
    prioridad: PRIORITY.MEDIA,
    fecha: '2026-03-26T16:20:00',
    ciudadano: 'Sofía Ramírez',
    telefono: '555-0107',
    direccion: 'Parque Col. Flores Magón',
    operador: null,
    tecnicoResponsable: null,
    lat: 19.4380,
    lng: -99.1290,
    arrivalTime: null,
    finishTime: null,
    technicalNotes: null,
    materialsUsed: null,
    resolutionResult: null,
    operatorSignature: null,
    evidence: null,
    images: [],
  },
  {
    _id: 8,
    id: 'DEN-2026-008',
    titulo: 'Drenaje colapsado',
    descripcion: 'Alcantarilla tapada provoca inundación en la calle cada vez que llueve.',
    categoria: 'Agua y drenaje',
    area: 'Área de Agua y Drenaje',
    estado: DENUNCIA_STATUS.EN_PROCESO,
    prioridad: PRIORITY.ALTA,
    fecha: '2026-03-24T13:50:00',
    ciudadano: 'Fernando Díaz',
    telefono: '555-0108',
    direccion: 'Calle Allende #67, Col. Norte',
    operador: 'Juan Pérez',
    tecnicoResponsable: 'Juan Pérez',
    lat: 19.4400,
    lng: -99.1360,
    arrivalTime: '2026-03-25T09:30:00',
    finishTime: null,
    technicalNotes: 'Alcantarilla obstruida con material sólido (escombros). Se requiere equipo de succión de alta presión.',
    materialsUsed: null,
    resolutionResult: null,
    operatorSignature: null,
    evidence: null,
    images: [
      { id: 4, url: 'https://placehold.co/600x400/4ac1e0/ffffff?text=ANTES+drenaje', type: 'BEFORE' },
    ],
  },
  {
    _id: 9,
    id: 'DEN-2026-009',
    titulo: 'Poste de luz inclinado',
    descripcion: 'Poste de concreto inclinado tras choque vehicular, riesgo de caída.',
    categoria: 'Alumbrado público',
    area: 'Área de Alumbrado Público',
    estado: DENUNCIA_STATUS.RECHAZADA,
    prioridad: PRIORITY.ALTA,
    fecha: '2026-03-23T10:05:00',
    ciudadano: 'Diego Hernández',
    telefono: '555-0109',
    direccion: 'Blvd. Las Palmas km 3',
    operador: 'María García',
    tecnicoResponsable: null,
    lat: 19.4245,
    lng: -99.1455,
    arrivalTime: null,
    finishTime: null,
    technicalNotes: null,
    materialsUsed: null,
    resolutionResult: null,
    operatorSignature: null,
    evidence: null,
    images: [],
  },
  {
    _id: 10,
    id: 'DEN-2026-010',
    titulo: 'Transporte público sin parada oficial',
    descripcion: 'Camiones se detienen en medio de la avenida por falta de parada señalizada.',
    categoria: 'Transporte',
    area: 'Área de Tránsito',
    estado: DENUNCIA_STATUS.RESUELTA,
    prioridad: PRIORITY.BAJA,
    fecha: '2026-03-22T09:30:00',
    ciudadano: 'Verónica Cruz',
    telefono: '555-0110',
    direccion: 'Av. Universidad esq. Calle 4',
    operador: 'Juan Pérez',
    tecnicoResponsable: 'Juan Pérez',
    lat: 19.4330,
    lng: -99.1500,
    arrivalTime: '2026-03-22T14:00:00',
    finishTime: '2026-03-23T11:00:00',
    technicalNotes: 'Se instaló señalización de parada oficial y delimitación en pavimento.',
    materialsUsed: 'Señal metálica, pintura amarilla, tornillería',
    resolutionResult: 'Parada instalada y señalizada correctamente. Ruta notificada.',
    operatorSignature: null,
    evidence: null,
    images: [
      { id: 5, url: 'https://placehold.co/600x400/4ac1e0/ffffff?text=ANTES+parada', type: 'BEFORE' },
      { id: 6, url: 'https://placehold.co/600x400/22c55e/ffffff?text=DESPUÉS+parada', type: 'AFTER' },
    ],
  },
  {
    _id: 11,
    id: 'DEN-2026-011',
    titulo: 'Grafiti en fachada de edificio público',
    descripcion: 'Vandalismo con pintura en aerosol en la biblioteca municipal.',
    categoria: 'Espacios públicos',
    area: 'Área de Espacios Públicos',
    estado: DENUNCIA_STATUS.PENDIENTE,
    prioridad: PRIORITY.BAJA,
    fecha: '2026-03-27T15:40:00',
    ciudadano: 'Ricardo Vargas',
    telefono: '555-0111',
    direccion: 'Biblioteca Municipal, Col. Centro',
    operador: null,
    tecnicoResponsable: null,
    lat: 19.4315,
    lng: -99.1375,
    arrivalTime: null,
    finishTime: null,
    technicalNotes: null,
    materialsUsed: null,
    resolutionResult: null,
    operatorSignature: null,
    evidence: null,
    images: [],
  },
  {
    _id: 12,
    id: 'DEN-2026-012',
    titulo: 'Falta de recolección de basura',
    descripcion: 'El camión recolector no ha pasado en 5 días por la colonia.',
    categoria: 'Basura y limpieza',
    area: 'Área de Limpieza y Residuos',
    estado: DENUNCIA_STATUS.EN_PROCESO,
    prioridad: PRIORITY.MEDIA,
    fecha: '2026-03-26T08:00:00',
    ciudadano: 'Elena Castillo',
    telefono: '555-0112',
    direccion: 'Col. Las Águilas, sector 3',
    operador: 'María García',
    tecnicoResponsable: null,
    lat: 19.4360,
    lng: -99.1440,
    arrivalTime: '2026-03-27T08:00:00',
    finishTime: null,
    technicalNotes: 'Ruta reprogramada. Recolección reiniciada.',
    materialsUsed: null,
    resolutionResult: null,
    operatorSignature: null,
    evidence: null,
    images: [],
  },
]

export const MOCK_STATS = {
  total:      MOCK_DENUNCIAS.length,
  pendientes: MOCK_DENUNCIAS.filter((d) => d.estado === DENUNCIA_STATUS.PENDIENTE).length,
  enProceso:  MOCK_DENUNCIAS.filter((d) => d.estado === DENUNCIA_STATUS.EN_PROCESO).length,
  resueltas:  MOCK_DENUNCIAS.filter((d) => d.estado === DENUNCIA_STATUS.RESUELTA).length,
  rechazadas: MOCK_DENUNCIAS.filter((d) => d.estado === DENUNCIA_STATUS.RECHAZADA).length,
  urgentes:   MOCK_DENUNCIAS.filter((d) => d.prioridad === PRIORITY.URGENTE).length,
}

// ── Datos de gráficas para Dashboard ──────────────────────────────────────────
export const MOCK_REPORT_BY_STATUS = {
  results: [
    { name: 'Pendiente',   count: 5, percentage: 41.7 },
    { name: 'En proceso',  count: 4, percentage: 33.3 },
    { name: 'Resuelta',    count: 2, percentage: 16.7 },
    { name: 'Cancelada',   count: 1, percentage: 8.3  },
  ],
}

export const MOCK_REPORT_BY_CATEGORY = {
  results: [
    { name: 'Baches y vialidad',  count: 18, percentage: 26.5 },
    { name: 'Agua y drenaje',     count: 14, percentage: 20.6 },
    { name: 'Alumbrado público',  count: 12, percentage: 17.6 },
    { name: 'Basura y limpieza',  count: 10, percentage: 14.7 },
    { name: 'Ruido excesivo',     count: 7,  percentage: 10.3 },
    { name: 'Espacios públicos',  count: 5,  percentage: 7.4  },
    { name: 'Transporte',         count: 2,  percentage: 2.9  },
  ],
}

// ── Usuarios (formato frontend mapeado) ───────────────────────────────────────
export const MOCK_USERS_LIST = [
  {
    id: 1,
    name: 'Ana Rodríguez',
    names: 'Ana',
    lastname: 'Rodríguez',
    secondLastname: 'Flores',
    ci: '1234567',
    phone: '555-0001',
    birthdate: '1985-04-15',
    gender: 'Femenino',
    email: 'admin@municipio.gob',
    roleId: 1,
    roleRaw: 'Administrador',
    unitId: null,
    area: null,
    active: true,
  },
  {
    id: 2,
    name: 'María García',
    names: 'María',
    lastname: 'García',
    secondLastname: 'López',
    ci: '2345678',
    phone: '555-0002',
    birthdate: '1992-08-20',
    gender: 'Femenino',
    email: 'operador@municipio.gob',
    roleId: 2,
    roleRaw: 'Operador de Call Center',
    unitId: 1,
    area: 'Área de Vialidad',
    active: true,
  },
  {
    id: 3,
    name: 'Juan Pérez',
    names: 'Juan',
    lastname: 'Pérez',
    secondLastname: 'Torres',
    ci: '3456789',
    phone: '555-0003',
    birthdate: '1990-12-05',
    gender: 'Masculino',
    email: 'campo@municipio.gob',
    roleId: 3,
    roleRaw: 'Personal de Campo',
    unitId: 2,
    area: 'Área de Agua y Drenaje',
    active: true,
  },
  {
    id: 4,
    name: 'Sandra Morales',
    names: 'Sandra',
    lastname: 'Morales',
    secondLastname: 'Ruiz',
    ci: '4567890',
    phone: '555-0004',
    birthdate: '1988-03-10',
    gender: 'Femenino',
    email: 'sandra.morales@municipio.gob',
    roleId: 2,
    roleRaw: 'Operador de Call Center',
    unitId: 3,
    area: 'Área de Alumbrado Público',
    active: true,
  },
  {
    id: 5,
    name: 'Roberto Vega',
    names: 'Roberto',
    lastname: 'Vega',
    secondLastname: 'Sánchez',
    ci: '5678901',
    phone: '555-0005',
    birthdate: '1995-06-22',
    gender: 'Masculino',
    email: 'roberto.vega@municipio.gob',
    roleId: 3,
    roleRaw: 'Personal de Campo',
    unitId: 4,
    area: 'Área de Limpieza y Residuos',
    active: false,
  },
]

// ── Unidades/Áreas operativas ──────────────────────────────────────────────────
export const MOCK_UNITS = [
  { id: 1, name: 'Área de Vialidad',            description: 'Mantenimiento de calles, baches y señalización vial' },
  { id: 2, name: 'Área de Agua y Drenaje',      description: 'Redes de agua potable, drenaje y alcantarillado' },
  { id: 3, name: 'Área de Alumbrado Público',   description: 'Mantenimiento e instalación de luminarias públicas' },
  { id: 4, name: 'Área de Limpieza y Residuos', description: 'Recolección de basura y limpieza de espacios' },
  { id: 5, name: 'Área de Espacios Públicos',   description: 'Parques, plazas y mobiliario urbano' },
  { id: 6, name: 'Área de Tránsito',            description: 'Regulación del tránsito y transporte público' },
]

// ── Departamentos ──────────────────────────────────────────────────────────────
export const MOCK_DEPARTMENTS = [
  { id: 1, name: 'Departamento de Infraestructura',    description: 'Obras civiles y mantenimiento urbano' },
  { id: 2, name: 'Departamento de Servicios Públicos', description: 'Servicios básicos para la ciudadanía' },
  { id: 3, name: 'Departamento de Medio Ambiente',     description: 'Gestión ambiental y residuos sólidos' },
  { id: 4, name: 'Departamento de Movilidad Urbana',   description: 'Tránsito, vialidad y transporte' },
]

// ── Categorías (con unidad asociada) ──────────────────────────────────────────
export const MOCK_CATEGORIES = [
  { id: 1,  name: 'Baches y vialidad',     unit: { id: 1, name: 'Área de Vialidad' } },
  { id: 2,  name: 'Señalización vial',     unit: { id: 1, name: 'Área de Vialidad' } },
  { id: 3,  name: 'Agua y drenaje',        unit: { id: 2, name: 'Área de Agua y Drenaje' } },
  { id: 4,  name: 'Fugas de agua',         unit: { id: 2, name: 'Área de Agua y Drenaje' } },
  { id: 5,  name: 'Alumbrado público',     unit: { id: 3, name: 'Área de Alumbrado Público' } },
  { id: 6,  name: 'Basura y limpieza',     unit: { id: 4, name: 'Área de Limpieza y Residuos' } },
  { id: 7,  name: 'Recolección de basura', unit: { id: 4, name: 'Área de Limpieza y Residuos' } },
  { id: 8,  name: 'Espacios públicos',     unit: { id: 5, name: 'Área de Espacios Públicos' } },
  { id: 9,  name: 'Parques y jardines',    unit: { id: 5, name: 'Área de Espacios Públicos' } },
  { id: 10, name: 'Ruido excesivo',        unit: { id: 6, name: 'Área de Tránsito' } },
  { id: 11, name: 'Transporte público',    unit: { id: 6, name: 'Área de Tránsito' } },
]

// ── Empresas/Compañías ─────────────────────────────────────────────────────────
export const MOCK_COMPANIES = [
  { id: 1, name: 'Municipio Central' },
  { id: 2, name: 'SAPEM (Agua y Drenaje)' },
  { id: 3, name: 'Empresa Eléctrica Municipal' },
]

// ── Datos para AdminReportes ───────────────────────────────────────────────────
export const MOCK_EFFICIENCY = {
  resolutionIndex: 72,
  averageResponseTimeSeconds: 14400, // 4 horas
  topCategories: [
    { name: 'Baches y vialidad', count: 18 },
    { name: 'Agua y drenaje',    count: 14 },
    { name: 'Alumbrado público', count: 12 },
  ],
}

export const MOCK_REPORT_BY_STATUS_FULL = {
  total: 12,
  results: [
    { name: 'Pendiente',   count: 5, percentage: 41.7 },
    { name: 'En proceso',  count: 4, percentage: 33.3 },
    { name: 'Resuelta',    count: 2, percentage: 16.7 },
    { name: 'Cancelada',   count: 1, percentage: 8.3  },
  ],
}

export const MOCK_REPORT_BY_CATEGORY_FULL = {
  results: [
    { name: 'Baches y vialidad',  count: 18, percentage: 26.5 },
    { name: 'Agua y drenaje',     count: 14, percentage: 20.6 },
    { name: 'Alumbrado público',  count: 12, percentage: 17.6 },
    { name: 'Basura y limpieza',  count: 10, percentage: 14.7 },
    { name: 'Ruido excesivo',     count: 7,  percentage: 10.3 },
    { name: 'Espacios públicos',  count: 5,  percentage: 7.4  },
    { name: 'Transporte',         count: 2,  percentage: 2.9  },
  ],
}

export const MOCK_REPORT_BY_OFFICE = {
  results: [
    { name: 'Área de Vialidad',            count: 20, percentage: 29.4 },
    { name: 'Área de Agua y Drenaje',      count: 17, percentage: 25.0 },
    { name: 'Área de Alumbrado Público',   count: 12, percentage: 17.6 },
    { name: 'Área de Limpieza y Residuos', count: 10, percentage: 14.7 },
    { name: 'Área de Espacios Públicos',   count: 6,  percentage: 8.8  },
    { name: 'Área de Tránsito',            count: 3,  percentage: 4.4  },
  ],
}

export const MOCK_REPORT_BY_RECEPTIONIST = {
  results: [
    { name: 'María García',  count: 7, percentage: 58.3 },
    { name: 'Juan Pérez',    count: 3, percentage: 25.0 },
    { name: 'Sandra Morales',count: 2, percentage: 16.7 },
  ],
}

export const MOCK_REPORT_BY_DISTRICT = {
  results: [
    { name: 'Distrito 1 - Centro',     count: 5, percentage: 41.7 },
    { name: 'Distrito 2 - Norte',      count: 3, percentage: 25.0 },
    { name: 'Distrito 3 - Sur',        count: 2, percentage: 16.7 },
    { name: 'Distrito 4 - Este',       count: 1, percentage: 8.3  },
    { name: 'Distrito 5 - Oeste',      count: 1, percentage: 8.3  },
  ],
}

// ── Gráficas legacy (compatibilidad) ──────────────────────────────────────────
export const MOCK_CHART_SEMANAL = [
  { dia: 'Lun', denuncias: 5, resueltas: 3 },
  { dia: 'Mar', denuncias: 8, resueltas: 5 },
  { dia: 'Mié', denuncias: 4, resueltas: 4 },
  { dia: 'Jue', denuncias: 7, resueltas: 2 },
  { dia: 'Vie', denuncias: 10, resueltas: 6 },
  { dia: 'Sáb', denuncias: 3, resueltas: 3 },
  { dia: 'Dom', denuncias: 2, resueltas: 1 },
]

export const MOCK_CHART_CATEGORIAS = [
  { categoria: 'Baches',      cantidad: 18 },
  { categoria: 'Agua/Drenaje',cantidad: 14 },
  { categoria: 'Alumbrado',   cantidad: 12 },
  { categoria: 'Basura',      cantidad: 10 },
  { categoria: 'Ruido',       cantidad: 7  },
  { categoria: 'Espacios',    cantidad: 5  },
  { categoria: 'Transporte',  cantidad: 4  },
  { categoria: 'Seguridad',   cantidad: 3  },
]
